version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    networks:
      - elastic
  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.0
    ports:
      - "5601:5601"
    networks:
      - elastic
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - elastic
    depends_on:
      - elasticsearch
      - mongo
  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - elastic
volumes:
  mongodb-data:
networks:
  elastic:
    driver: bridge